### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Shikomi36** [Theotoma/Anti-AFK#3]
Does it work on multiple instances of roblox, and if not could you make this a feature?

**Comment by Theotoma** [comment]
This seems to be a rather popular request: I'll into into adding support

**Comment by Theotoma** [comment]
This isn't abandoned by the way: I've decided to fully rewrite Anti-AFK and it's almost done
The latest version includes support for multiple instances **as well as** processes
I just need to finish up and test a few things before I commit and push it

**Comment by Theotoma** [comment]
This should now be implemented (0d81e7a4ab309a5aa26425b391c15efea7649c5c)
If there are any issues please let me know
