### ISSUE TITLE
should i update to the new version

### ISSUE THREAD

**Issue by russyboy1** [Theotoma/Anti-AFK#6]
should i update to the newest version, my version was downloaded on 27 apr
thanks

**Comment by russyboy1** [comment]
and i find this script pretty ez to use
thanks to the maker

**Comment by russyboy1** [comment]
i could use the built in feature of autohotkey to make the .ahk file to an .exe , that makes me easier to open it to use or pin it to the windows start screen

**Comment by russyboy1** [comment]
very easy to use, very good and never crashes :)

**Comment by Theotoma** [comment]
Hi! Thanks for the feedback :)

In general, you should always use the latest version of anything. The latest version of Anti-AFK is a complete rewrite and is far more customizable than the old version - in addition to being higher-quality code and supporting multi-instance.

Feel free to compile it into an exe, although if you're feeling lazy you can always move the script to the [startup folder](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd).
I prefer running the source directly, but - at the end of the day - it's up to you.

**Comment by russyboy1** [comment]
thank you very much! :D
